### ISSUE TITLE
简历问题

### ISSUE THREAD

**Issue by gamedebug** [wangchunhui521/daima#1]
项目具体情况呢？维护大规模的环境？shell给谁写？在多少节点上抓系统信息？用户是谁？他们用你们的系统干嘛？用户的业务是什么？访问量/使用量多大？你运维团队什么规模？怎么分工？你具体负责哪块？你负责的这部分工作需要哪些技能支撑？你有日常工作么？故障排除经验有么？优化会做么？为什么要排故？为什么要优化？为什么会有故障？

**Comment by wangchunhui521** [comment]
老师，下周一交新版本的简历

> 项目具体情况呢？维护大规模的环境？shell给谁写？在多少节点上抓系统信息？用户是谁？他们用你们的系统干嘛？用户的业务是什么？访问量/使用量多大？你运维团队什么规模？怎么分工？你具体负责哪块？你负责的这部分工作需要哪些技能支撑？你有日常工作么？故障排除经验有么？优化会做么？为什么要排故？为什么要优化？为什么会有故障？

老师，下周一交新版本简历
